console.log(typeof(1))  //number 
console.log(typeof('hello')) //string
console.log(typeof(true)) //boolean 
 console.log(typeof(undefined)) //undefined
console.log(typeof(Symbol('1'))) //symbol
console.log(typeof(function(){})) //function 
console.log(typeof([1,2,3,4]))// object 
console.log(typeof(null))    //object
console.log(typeof({name:'lili'})) //Object